name: Docker container Test

on:
  push:
      paths:
         - '**.c'
         - 'Makefile'
         
jobs:
  docker_tests:
      runs-on: ubuntu-latest
      
      steps:
         - name: Checkout
           uses: actions/checkout@v3
         
         - name: Prepare target of binaries 
           run: make build_bin_dir
             
         - name: Run Docker
           run: docker run --rm --mount type=bind,source=${PWD},target=/app/test danielsp13/lamport
