name: Análisis de fugas de memoria con Valgrind

on:
  push:
      paths:
         - '**.h'
         - '**.c'
         - '**.lmp'
         - 'Makefile'
         
jobs:
  mem_check:
      runs-on: ubuntu-latest
      
      steps:
         - name: Checkout
           uses: actions/checkout@v3
           
         - name: Caché de paquetes apt
           id: cache-apt
           uses: actions/cache@v2
           with:
            path: |
              /var/lib/apt/lists/
              /var/cache/apt/archives/
            key: ${{ runner.os }}-apt-${{ hashFiles('**/Makefile') }}
             
         - name: Instalar dependencias de compilación y testeo
           if: steps.cache-apt.outputs.cache-hit != 'true'
           run: make install_source_dependencies
         
         - name: Construir compilador
           run: make
           
         - name: Ejecutar tests de Valgrind con parallel
           run: make tests_parallel
