name: Compilación y testeo de módulos

on:
  push:
      paths:
         - '**.c'
         - 'Makefile'
         
jobs:
  build_and_test:
      runs-on: ubuntu-latest
      
      steps:
         - name: Checkout
           uses: actions/checkout@v3
             
         - name: Caché de paquetes apt
           id: cache-apt
           uses: actions/cache@v2
           with:
            path: |
              /var/lib/apt/lists/
              /var/cache/apt/archives/
            key: ${{ runner.os }}-apt-${{ hashFiles('**/Makefile') }}
             
         - name: Instalar dependencias de compilación y testeo
           if: steps.cache-apt.outputs.cache-hit != 'true'
           run: make install_source_dependencies
           
         - name: Compilar modulos
           run: make compile_sources
           
         - name: Compilar tests
           run: make compile_tests
           
         - name: Ejecutar tests de modulo -- lexer
           run: make test_lexer
