name: Publicar contenedor Docker Lamport

on:
  push:
      paths:
         - '**.h'
         - '**.c'
         - 'Makefile'
         - 'Dockerfile'
         
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar Git
      uses: actions/checkout@v2

    - name: Iniciar Docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir imagen Docker
      run: |
        make build_docker

  publish:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Iniciar Docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Publicar imagen Docker
      run: |
        docker push lamport:latest
