name: Publicar contenedor Docker Lamport

on:
  push:
    branches:
      - main
    paths:
      - '**.h'
      - '**.c'
      - 'Makefile'
      - 'Dockerfile'
  pull_request:
    types:
      - closed
         
jobs:
  build_and_push:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Login to Docker Hub
           uses: docker/login-action@v2
           with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}

         - name: Build and push
           uses: docker/build-push-action@v4
           with:
               push: true
               tags: danielsp13/lamport
